subscription                   = "4af28428-fadd-42d1-ba1c-ba3eef6d4a6c"
ise_resource_group             = "ise_dev"
location                       = "East US"
vnet_name                      = "esc_VNet"
ise_lb_subnet_name             = "default"
ise_vmss_subnet_name           = "Peter2_subnet"
ise_vmss_private_dns_zone_name = "example.com"