name: Bug Report
description: If something isn't working as expected.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report.

        If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions).

        Please also note the following potential times when an issue might be in Terraform core:

        * [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
        * [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
        * [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
        * [Registry](https://registry.terraform.io/) issues
        * Spans resources across multiple providers

        If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: terraform
    attributes:
      label: Terraform Version
      description: Which Terraform version are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: azurerm
    attributes:
      label: AzureRM Provider Version
      description: Which AzureRM Provider version are you using?
      placeholder: 3.0.0
    validations:
      required: true
  - type: input
    id: resource
    attributes:
      label: Affected Resource(s)/Data Source(s)
      description: Please list the affected resources and/or data sources.
      placeholder: azurerm_XXXXX
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Terraform Configuration Files
      description: |
        Please provide a minimal Terraform configuration that can reproduce the issue.
      render: hcl
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should have happened?
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the steps required to reproduce the issue, e.g.

        1. `terraform apply`