name: Feature Request
description: I have a suggestion (and might want to implement myself)!
title: "Support for [thing]"
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please leave a helpful description of the feature request here.
    validations:
      required: true
  - type: input
    id: resource
    attributes:
      label: New or Affected Resource(s)/Data Source(s)
      description: Please list the new or affected resources and/or data sources.
      placeholder: azurerm_XXXXX
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Potential ISE Automation Configuration
      description: Please provide an example of what the new resource or enhancement could look like in a ISE Automation.
      render: hcl